# Generated by Django 4.1.7 on 2023-04-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0014_order_razor_pay_order_id_order_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amt',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
